name: php
version: 6.1.3
schema: 1
scm: github.com/pubnub/php
changelog:
  - date: 2023-11-27
    version: v6.1.3
    changes:
      - type: bug
        text: "Gracefully handle decrypting an unencrypted method. If a decryption error occurs when trying to decrypt plain text, the plain text message will be returned and an error field will be set in the response. This works for both history and subscription messages."
  - date: 2023-11-02
    version: v6.1.2
    changes:
      - type: improvement
        text: "Fix license info in composer.json" 
  - date: 2023-10-30
    version: v6.1.1
    changes:
      - type: bug
        text: "Changed license type from MIT to PubNub Software Development Kit License."
  - date: 2023-10-16
    version: v6.1.0
    changes:
      - type: feature
        text: "Add crypto module that allows configure SDK to encrypt and decrypt messages."
      - type: bug
        text: "Improved security of crypto implementation by adding enhanced AES-CBC cryptor."
  - date: 2023-05-18
    version: v6.0.1
    changes:
      - type: bug
        text: "Support for Monolog/Monolog@^3.0."
      - type: bug
        text: "Added replacement for deprecated utf8_decode method."
  - date: 2023-02-01
    version: v6.0.0
    changes:
      - type: improvement
        text: "BREAKING CHANGES: This update is intended to bring compatibility with PHP 8.2 and newer versions of dependencies."
  - date: 2022-08-30
    version: v5.1.0
    changes:
      - type: feature
        text: "Add option to initialize PubNub with UserId."
  - date: 2022-01-26
    version: v5.0.0
    changes:
      - type: improvement
        text: "BREAKING CHANGES: Disable automated uuid generation and make it mandatory to specify before `PubNub` instance creation."
  - date: 2021-12-16
    version: v4.7.0
    changes:
      - type: feature
        text: "RevokeToken method."
      - type: bug
        text: "Fixed error in Signal request."
  - version: v4.6.0
    date: 2021-10-26
    changes:
      -
        text: "Add support for Access Manager v3 with example."
        type: feature
  - version: v4.5.0
    date: 2021-08-24
    changes:
      -
        text: "Missing PNPresenceEventResult getters added, dependency update."
        type: feature
  - version: v4.4.0
    date: 2021-07-29
    changes:
      -
        text: "Fix for wrong signature calculation mechanism added."
        type: feature
  - version: v4.3.0
    date: 2021-03-21
    changes:
      -
        text: "Add support for random initialization vector."
        type: feature
  - version: v4.2.0
    date: 2021-02-02
    changes:
      -
        text: "Add support for device channel registration with apns2."
        type: feature
      -
        text: "Allows management of users and channels with metadata."
        type: feature
      -
        text: "Implement v2 signatures required for push and objects."
        type: feature
      -
        text: "Implement v2 grant endpoint with support for user level grant."
        type: feature
  - version: v4.1.7
    date: 2020-09-14
    changes:
      -
        text: "Add delete permission support to grant call."
        type: feature
  - version: v4.1.6
    date: 2020-08-20
    changes:
      -
        text: "Remove hard coded keys from tests."
        type: improvement
  - version: 4.1.5
    date: 2019-10-22
    changes:
      - type: improvement
        text: Update composer.json package version constraints
      - type: improvement
        text: Update .travis.yml to run tests for PHP versions 7.2 and 7.3
  - version: 4.1.4
    date: 2019-10-18
    changes:
      - type: bug
        text: Add support for request transport reusing to resolve slow publish issues when multiple messages are published consecutively.
      - type: bug
        text: Drop support for HHVM.
  - version: 4.1.3
    date: 2019-02-28
    changes:
      - type: feature
        text: Add messageCounts() method for retrieving unread message count
  - version: 4.1.2
    date: 2018-10-23
    changes:
      - type: bug
        text: Fix issue with deleteMessages endpoint using GET HTTP method instead of DELETE
  - version: 4.1.1
    date: 2018-10-02
    changes:
      - type: feature
        text: Add setOrigin method
      - type: improvement
        text: Add .gitattributes file to save space when using composer
      - type: bug
        text: Fix urlencode issue with channel names
      - type: bug
        text: Fix channel name validation for Publish
      - type: bug
        text: Return class instance of PNConfiguration on setConnectTimeout method
  - version: 4.1.0
    date: 2018-09-07
    changes:
      - type: feature
        text: Add fire() method on PubNub instance
      - type: bug
        text: Change return value of SetState::getOperationType
      - type: feature
        text: Add history delete (deleteMessages) method on PubNub instance
      - type: feature
        text: Add Telemetry Manager
  - version: 4.0.0
    date: 2017-06-07
    changes:
      - type: feature
        text: release final v4
      - type: bug
        text: Fix publish sequence counter
      - type: bug
        text: Fix publish tests
  - version: 4.0.0-beta.3
    date: 2017-05-05
    changes:
      - type: bug
        text: Fix special characters encoding
      - type: bug
        text: Remove set* prefix from publish setters
  - version: 4.0.0-beta.2
    date: 2017-04-21
    changes:
      - type: bug
        text: Add missing methods on PubNub instance
      - type: bug
        text: Fix removeAllPushChannelsForDevice method case
  - version: 4.0.0-beta
    date: 2017-04-18
    changes:
      - type: bug
        text: Fix windows compatibility
      - type: improvement
        text: Add option to disable SSL
      - type: bug
        text: Fix subscribe presence response parsing
      - type: bug
        text: Add missing removeListener()
      - type: improvement
        text: Add logger
      - type: bug
        text: Fix json decoding error
      - type: improvement
        text: Add Push methods
  - version: 4.0.0-alpha
    date: 2017-04-04
    changes:
      - type: improvement
        text: Alpha Release
features:
  access:
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-FIRE
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
    - PUSH-TYPE-APNS
    - PUSH-TYPE-APNS2
    - PUSH-TYPE-FCM
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-MESSAGE-COUNT
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-PUBLISHER-UUID

supported-platforms:
  -
    version: PubNub PHP SDK
    platforms:
      - FreeBSD 8-STABLE or later, amd64, 386
      - Linux 2.6 or later, amd64, 386.
      - Mac OS X 10.8 or later, amd64
      - Windows 7 or later, amd64, 386
    editors:
      - PHP 5.6
      - PHP 7.0
      - PHP 7.1
      - PHP 7.2
      - PHP 7.3
sdks:
  - full-name: PHP SDK
    short-name: PHP
    artifacts:
      - artifact-type: api-client
        language: PHP
        tier: 2
        tags:
          - Server
        source-repository: https://github.com/pubnub/php
        documentation: https://www.pubnub.com/docs/sdks/php
        distributions:
          - distribution-type: source
            distribution-repository: GitHub
            package-name: PubNub PHP SDK
            location: https://github.com/pubnub/php
            requires:
              - name: rmccue/requests
                min-version: 1.0.0
                max-version: 1.8.0
                location: https://packagist.org/packages/rmccue/requests
                license: ISC license
                license-url: https://github.com/WordPress/Requests/blob/master/LICENSE
                is-required: Required
                notes: Will be installed along with SDK
              - name: monolog/monolog
                min-version: 1.0.0
                max-version: 1.22.1
                location: https://github.com/Seldaek/monolog
                license: MIT License
                license-url: https://github.com/Seldaek/monolog/blob/main/LICENSE
                is-required: Required
                notes: Will be installed along with SDK
            supported-platforms:
              supported-operating-systems:
                macOS:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Mac OS X 10.8
                  maximum-os-version:
                    - macOS 11.2.3
                  target-architecture:
                    - arm64
                    - x86-64
                Windows:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Windows 7 Professional
                    - Windows 7 Enterprise
                    - Windows 7 Ultimate
                  maximum-os-version:
                    - Windows 10 Pro
                    - Windows 10 Enterprise
                  target-architecture:
                    - x86
                    - x86-64
                Linux:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Ubuntu 16.04 LTS
                  maximum-os-version:
                    - Ubuntu 18.04 LTS
                  target-architecture:
                    - x86
                    - x86-64
          - distribution-type: package
            distribution-repository: Packagist
            package-name: pubnub/pubnub
            location: https://packagist.org/packages/pubnub/pubnub
            requires:
              - name: rmccue/requests
                min-version: 1.0.0
                max-version: 1.8.0
                location: https://packagist.org/packages/rmccue/requests
                license: ISC license
                license-url: https://github.com/WordPress/Requests/blob/master/LICENSE
                is-required: Required
                notes: Will be installed along with SDK
              - name: monolog/monolog
                min-version: 1.0.0
                max-version: 1.22.1
                location: https://github.com/Seldaek/monolog
                license: MIT License
                license-url: https://github.com/Seldaek/monolog/blob/main/LICENSE
                is-required: Required
                notes: Will be installed along with SDK
            supported-platforms:
              supported-operating-systems:
                macOS:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Mac OS X 10.8
                  maximum-os-version:
                    - macOS 11.2.3
                  target-architecture:
                    - arm64
                    - x86-64
                Windows:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Windows 7 Professional
                    - Windows 7 Enterprise
                    - Windows 7 Ultimate
                  maximum-os-version:
                    - Windows 10 Pro
                    - Windows 10 Enterprise
                  target-architecture:
                    - x86
                    - x86-64
                Linux:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Ubuntu 16.04 LTS
                  maximum-os-version:
                    - Ubuntu 18.04 LTS
                  target-architecture:
                    - x86
                    - x86-64
          - distribution-type: library
            distribution-repository: GitHub release
            package-name: php-6.1.3.zip
            location: https://github.com/pubnub/php/releases/tag/v6.1.3
            requires:
              - name: rmccue/requests
                min-version: 1.0.0
                max-version: 1.8.0
                location: https://packagist.org/packages/rmccue/requests
                license: ISC license
                license-url: https://github.com/WordPress/Requests/blob/master/LICENSE
                is-required: Required
                notes: Will be installed along with SDK
              - name: monolog/monolog
                min-version: 1.0.0
                max-version: 1.22.1
                location: https://github.com/Seldaek/monolog
                license: MIT License
                license-url: https://github.com/Seldaek/monolog/blob/main/LICENSE
                is-required: Required
                notes: Will be installed along with SDK
            supported-platforms:
              supported-operating-systems:
                macOS:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Mac OS X 10.8
                  maximum-os-version:
                    - macOS 11.2.3
                  target-architecture:
                    - arm64
                    - x86-64
                Windows:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Windows 7 Professional
                    - Windows 7 Enterprise
                    - Windows 7 Ultimate
                  maximum-os-version:
                    - Windows 10 Pro
                    - Windows 10 Enterprise
                  target-architecture:
                    - x86
                    - x86-64
                Linux:
                  runtime-version:
                    - PHP 5.6
                    - PHP 7.0
                    - PHP 7.1
                    - PHP 7.2
                    - PHP 7.3
                  minimum-os-version:
                    - Ubuntu 16.04 LTS
                  maximum-os-version:
                    - Ubuntu 18.04 LTS
                  target-architecture:
                    - x86
                    - x86-64
