name: php
version: 4.0.0
schema: 1
scm: github.com/pubnub/php
changelog:
  - version: 4.0.0
    changes:
      - type: feature
        text: release final v4
  - version: 4.0.0-beta.3
    date:
    changes:
      - type: bug
        text: Fix special characters encoding
      - type: bug
        text: Remove set* prefix from publish setters
  - version: 4.0.0-beta.2
    date:
    changes:
      - type: bug
        text: Add missing methods on PubNub instance
      - type: bug
        text: Fix removeAllPushChannelsForDevice method case
  - version: 4.0.0-beta
    date:
    changes:
      - type: bug
        text: Fix windows compatibility
      - type: improvement
        text: Add option to disable SSL
      - type: bug
        text: Fix subscribe presence response parsing
      - type: bug
        text: Add missing removeListener()
      - type: improvement
        text: Add logger
      - type: bug
        text: Fix json decoding error
      - type: improvement
        text: Add Push methods
  - version: 4.0.0-alpha
    date:
    changes:
      - type: improvement
        text: Alpha Release
features:
  access:
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-PUBLISHER-UUID

supported-platforms:
  -
    version: PubNub PHP SDK
    platforms:
      - FreeBSD 8-STABLE or later, amd64, 386
      - Linux 2.6 or later, amd64, 386.
      - Mac OS X 10.8 or later, amd64
      - Windows 7 or later, amd64, 386
    editors:
      - php 5.6
      - php 7.0
      - php 7.1
      - hhvm
