
name: AcceptanceTests

on:
  push:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
      name: Perform Acceptance BDD tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout project
          uses: actions/checkout@v3
        - name: Checkout mock-server action
          uses: actions/checkout@v3
          with:
            repository: pubnub/client-engineering-deployment-tools
            ref: v1
            token: ${{ secrets.GH_TOKEN }}
            path: .github/.release/actions
        - name: Run mock server action
          uses: ./.github/.release/actions/actions/mock-server
          with:
            token: ${{ secrets.GH_TOKEN }}
        - name: Install Composer dev depenencies
          run: |
            composer install --dev
        - name: Run acceptance tests
          run: |
            mkdir -p tests/features/bootstrap/access/
            mkdir -p tests/features/bootstrap/utilities/
            mkdir -p tests/features/reports
            cp sdk-specifications/features/access/grant-token.feature tests/features/bootstrap/access/grant-an-access-token.feature
            cp sdk-specifications/features/utilities/time.feature tests/features/bootstrap/utilities/time.feature
            vendor/bin/behat -f junit -o tests/features/reports/
        - name: Expose acceptance tests reports
          uses: actions/upload-artifact@v2
          with:
            name: acceptance-test-reports
            path: ./tests/features/reports
