name: Tests

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Integration and Unit tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2]
    env:
      PUBLISH_KEY: ${{ secrets.PUBLISH_KEY }}
      SUBSCRIBE_KEY: ${{ secrets.SUBSCRIBE_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PUBLISH_PAM_KEY: ${{ secrets.PUBLISH_PAM_KEY }}
      SUBSCRIBE_PAM_KEY: ${{ secrets.SUBSCRIBE_PAM_KEY }}
      SECRET_PAM_KEY: ${{ secrets.SECRET_PAM_KEY }}
      UUID_MOCK: "test-user"
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Determine composer cache directory
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT
      - name: Cache Composer
        uses: actions/cache@v3
        with:
          path: |
            "${{ steps.composer-cache-dir.outputs.dir }}"
            ${{ github.workspace }}/vendor
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit
          coverage: none
      - name: Setup dependencies
        run: |
          composer self-update && composer --version
          composer install --prefer-dist
      - name: Run unit tests
        run: vendor/bin/phpunit --verbose
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
  all-tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Tests summary
        run: echo -e "\033[38;2;95;215;0m\033[1mAll tests successfully passed"
