name: Tests

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Integration and Unit tests
    runs-on:
      group: organization/Default
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
    env:
      PUBLISH_KEY: ${{ secrets.SDK_PUB_KEY }}
      SUBSCRIBE_KEY: ${{ secrets.SDK_SUB_KEY }}
      SECRET_KEY: ${{ secrets.SDK_SEC_KEY }}
      PUBLISH_PAM_KEY: ${{ secrets.SDK_PAM_PUB_KEY }}
      SUBSCRIBE_PAM_KEY: ${{ secrets.SDK_PAM_SUB_KEY }}
      SECRET_PAM_KEY: ${{ secrets.SDK_PAM_SEC_KEY }}
      UUID_MOCK: "test-user"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Determine composer cache directory
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT
      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            "${{ steps.composer-cache-dir.outputs.dir }}"
            ${{ github.workspace }}/vendor
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit
          coverage: none
      - name: Setup dependencies
        run: |
          composer self-update && composer --version
          composer install --prefer-dist
      - name: Run unit tests
        run: composer test
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
  acceptance-tests:
    name: Perform Acceptance BDD tests
    runs-on:
      group: organization/Default
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Checkout mock-server action
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Run mock server action
        uses: ./.github/.release/actions/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install Composer dev depenencies
        run: |
          composer install --dev
      - name: Run acceptance tests
        run: |
          composer acceptance-test
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-test-reports
          path: ./tests/Acceptance/reports
  all-tests:
    name: Tests
    needs: [tests]
    runs-on:
      group: organization/Default
    steps:
      - name: Tests summary
        run: echo -e "\033[38;2;95;215;0m\033[1mAll tests successfully passed"
