name: run_acceptance_tests

on: [push]

jobs:
  build:
      name: Perform Acceptance BDD tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout project
          uses: actions/checkout@v2
        - name: Checkout mock-server action
          uses: actions/checkout@v2
          with:
            repository: pubnub/client-engineering-deployment-tools
            ref: github-actions
            token: ${{ secrets.GH_TOKEN }}
            path: client-engineering-deployment-tools
        - name: Run mock server action
          uses: ./client-engineering-deployment-tools/actions/mock-server
          with:
            token: ${{ secrets.GH_TOKEN }}
        - name: Install Composer dev depenencies
          run: |
            COMPOSER=acceptance.json composer install --dev
        - name: Run acceptance tests
          run: |
            mkdir -p tests/features/bootstrap/access/
            mkdir -p tests/features/bootstrap/utilities/
            mkdir -p tests/features/reports
            cp sdk-specifications/features/access/grant-token.feature tests/features/bootstrap/access/grant-an-access-token.feature
            cp sdk-specifications/features/utilities/time.feature tests/features/bootstrap/utilities/time.feature
            vendor/bin/behat -f junit -o tests/features/reports/
        - name: Expose acceptance tests reports
          uses: actions/upload-artifact@v2
          with:
            name: acceptance-test-reports
            path: ./tests/features/reports